### ISSUE TITLE
Estructura web

### ISSUE THREAD

**Issue by Nekmo** [python-spain/web#10]
Una posible estructura en la web:

```
- Inicio
- Noticias
----- Eventos
- Comunidad
---- Personas (mapa y filtro donde se encuentra la gente)
---- Asociaciones (mapa y filtro con las asociaciones)
---- Planet
- Aprende Python
---- Desde cero
---- Recursos
- Asociación
---- Cómo hacerse miembro
---- Junta directiva
---- Patrocinadores
- Ofertas de trabajo
- FAQ
```

@Juanlu001 :
Idea (un poco de alto nivel): la web debería contestar estas preguntas

¿Quiénes forman la comunidad? -> ¿Mapa de comunidades?
¿Qué es la asociación?
¿Cómo me pongo en contacto con las dos anteriores? -> A veces la gente me escribe a mí porque no queda claro a quién enviar el email.
¿Cómo puedo colaborar? -> Tanto hacerse socio de la asociación, como montar una comunidad local, dar charlas, ayudar con la PyConES, nuestros proyectos en GitHub (portal de empleo, la web en sí, planet cuando exista)...
¿Cómo funciona la asociación? -> Enlace claro a los estatutos, reglamento, actas...
¿Cómo aprendo Python? -> Enlazando no solo recursos de aprendizaje y nuestros blogs en el planet sino también a las comunidades locales
¿Tiene la comunidad un código de conducta?

**Comment by italofarve** [comment]
A mi me parece bien. Ahora debemos priorizar e ir colocando la información poco a poco. He visto que el apartado FAQ (de la old web) respondía más a dudas sobre Python, pero es un buen material que nos puede servir para el apartado "Aprende Python". Asi dejamos al FAQ para responder a las preguntas que queden por contestar que comenta @Juanlu001 que lo veo más correcto.

**Comment by delapuente** [comment]
¿Alguna actualización aquí? ¿Alguien que quiera ponerse a migrar documentación? @python-spain/equipo-editor ?

**Comment by dukebody** [comment]
Vamos a intentar darle un empujoncito a esto. :)

Es un objetivo que me marqué para el primer trimestre de 2021: https://github.com/python-spain/asociacion/issues/126

Tenemos que añadir enlaces claros a Discourse: https://github.com/python-spain/web/issues/78

**Comment by dukebody** [comment]
Arreglado en la nueva web.
