### ISSUE TITLE
La sección de "aprende python" para sugerir mejoras / añadir enlaces apunta al repo de PMF

### ISSUE THREAD

**Issue by dukebody** [python-spain/web#101]
En https://github.com/python-spain/web/blob/master/content/pages/aprende-python.md se menciona que para solicitar contenido nuevo o mejorar/añadir una respuesta se abra issue/PR en https://github.com/python-spain/PMF. ¿No debería ser en este mismo repo, https://github.com/python-spain/web?

**Comment by quobit** [comment]
Además debería ser un único listado (y referenciar esta página de la web desde las PMF/FAQ). ¿Qué os parece?

**Comment by dukebody** [comment]
> Además debería ser un único listado (y referenciar esta página de la web desde las PMF/FAQ). ¿Qué os parece?

¡Me parece bien! @quobit , ¿puedes cambiar el PMF para que apunte a https://es.python.org/pages/aprende-python.html?

**Comment by quobit** [comment]
Hecho @dukebody.
