### ISSUE TITLE
Agregar sección de empleo a la web

### ISSUE THREAD

**Issue by dukebody** [python-spain/web#105]
Algunas ideas:
- Enlace a https://comunidad.es.python.org/c/empleo
- Algunos enlaces a recursos interesantes para preparar entrevistas / qué has de saber como https://www.youtube.com/watch?v=_D-wcRYzsHo o https://www.youtube.com/watch?v=7Oly98JFuCs
- Instrucciones breves sobre cómo publicar una oferta

**Comment by quobit** [comment]
También podría integrar la sección de PMF: https://github.com/python-spain/pmf#puedo-publicar-una-oferta-de-trabajo (como se ha hecho con la página de Aprende Python) y la información que devuelve Rose en el grupo de Telegram https://t.me/PythonEsp cuando se escribe _#ofertas_ en el grupo

**Comment by dukebody** [comment]
¡Sí! También podemos poner el enlace al Discord, que tiene las mismas reglas.

**Comment by dukebody** [comment]
¡Hecho!
