### ISSUE TITLE
La web del PyDay usa contenido inseguro

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/web#28]
https://es.python.org/pyday2016

![screenshot from 2017-09-27 11-01-20](https://user-images.githubusercontent.com/316517/30904774-3ae63874-a373-11e7-87e7-03e3ebea2e43.png)

cc @jespino

**Comment by delapuente** [comment]
¿Me puedes indicar cómo has llegado hasta ahí desde la web, por favor?

**Comment by astrojuanlu** [comment]
Metí la URL directamente

**Comment by delapuente** [comment]
🤔 Investigaré...

**Comment by jespino** [comment]
Y yo llegue a través de google buscando pyday

**Comment by delapuente** [comment]
No encuentro una sola referencia a este contenido en los fuentes de la web. No parece una redirección pero quizá sea algo que se quedó en el servidor y está desactualizado. @yamila-moreno ¿podrías mirar esto?

**Comment by Manosfrias** [comment]
Buenas, no la he encontrado en la copia local.

**Comment by yamila-moreno** [comment]
buenas! el pyday es una página estática aparte de la web de python españa. la sirve nginx directamente. ¿qué necesitáis?

**Comment by delapuente** [comment]
Al parecer está sirviendo contenido inseguro y parece que ha perdido la hoja de estilo. ¿Sería posible servir el contenido del que se queja sobre https?
![captura de pantalla 2018-07-07 a las 13 28 32](https://user-images.githubusercontent.com/757942/42410444-e8972474-81e9-11e8-8e0e-71b725166109.png)

**Comment by yamila-moreno** [comment]
He corregido los css y el logo por https; revisadlo y me decís :)

**Comment by astrojuanlu** [comment]
Confirmado :) ¡Cerrando! Mil gracias @yamila-moreno :pray:
