### ISSUE TITLE
Proposición sobre sección Historias

### ISSUE THREAD

**Issue by delapuente** [python-spain/web#29]
Historias: ¿tendría sentido agregar un apartado Historias? Anécdotas, historias de éxito, etc, sobre como la asociación influyo o provoco un cambio en nuestras vidas.

**Comment by astrojuanlu** [comment]
Tendría todo el sentido del mundo :) ¿Algo así? http://pyfound.blogspot.com.es/2017/08/the-ethical-maintainer-community.html

**Comment by delapuente** [comment]
Voy a cerrar esto a la espera de contenido que cuadre en esta clasificación aunque podemos recordarlo en la siguiente reunión de socios.
