### ISSUE TITLE
Simplificar página "Hazte socio"

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/web#36]
En la página "Hazte socio" hay mucha información sobre ya socios (cómo acompasar el pago, cómo domiciliar si no estaba domiciliada) que creo que solo agrega ruido a la gente que quiere solo asociarse. El IBAN de la asociación esá abajo del todo bajo un wall of text.

**Comment by astrojuanlu** [comment]
Relacionado: #22

**Comment by delapuente** [comment]
Cómo mejora rápida propongo reorganizar el texto para que primero esté el cómo hacerse socio y luego "otra información para socios". ¿Suena razonable?

**Comment by astrojuanlu** [comment]
Razonabilísimo!

**Comment by maigimenez** [comment]
Además de todo lo comentado, en la actualidad el proceso de verificación de altas y renovaciones es completamente manual e implica la gestión de tesorería y secretaría. En el futuro sería interesante automatizar este proceso. 
Este tema se trató en la reunión de la JD del 8 de abril y se refleja en el [acta](https://github.com/python-spain/actas/blob/master/acta-2018-04-08.rst) de la misma. Debido a su complejidad se propone posponerlo para abordarlo en un monográfico.
