### ISSUE TITLE
Falta informacion para contactar a la organizacion

### ISSUE THREAD

**Issue by mariocj89** [python-spain/web#37]
Deberiamos de tener un enlace al correo de la asociacion en la parte de patrocinadores, en caso de que nuevos patrocinadores esten interesados.

**Comment by delapuente** [comment]
¿A qué correo?

**Comment by astrojuanlu** [comment]
Buena pregunta. Lo hablo con @jcea.

**Comment by astrojuanlu** [comment]
contacto@es.python.org

**Comment by delapuente** [comment]
Hoy lo tenéis.

**Comment by delapuente** [comment]
Qué "hoy" más largo, leñe.
