### ISSUE TITLE
Considerar añadir Disqus a los artículos

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/web#4]

**Comment by astrojuanlu** [comment]
¿Podríamos evaluar Isso también?

https://posativ.org/isso/

Desventajas: requiere un servidor, y no vale un PaaS porque usa SQLite.

**Comment by kikocorreoso** [comment]
Yo estaría con un -10 a disqus por varios temas:

* privacidad
* sobrecarga de datos en redes móviles
* lentitud de descarga
* anuncios
* ejecutar código no requerido ni deseado en mi PC
* ...

Opciones:

* Isso, como dice Juanlu. Si funciona con AWS lambda y hay uno o ningún comentario a cada nuevo post, que tampoco son muy frecuentes, igual hasta sale gratuito ([El primer millón de solicitudes de cada mes es gratis](https://aws.amazon.com/es/lambda/pricing/)).
* Usar algo como [esto](https://getnikola.com/blog/really-static-comments-with-staticman.html).
* No tener comentarios.

Saludos.

**Comment by yamila-moreno** [comment]
Actualmente la web está en un servidor de la asociación donde se puede instalar software, solo hay que sacar tiempo y ganas de trastear un poco, ¿alguno se anima? Esto lo dockerizáis en un tris ;-)

**Comment by kikocorreoso** [comment]
Ya que he lanzado la piedra no voy a esconder la mano.

Yo no me dedico a ello (la web) pero si me dejáis brasearos con preguntas técnicas (por la lista PY_ES por ejemplo) no me importa meterme con ello. Si lo tengo que hacer yo solo sin guía prefiero no meterme.

**Comment by yamila-moreno** [comment]
Gracias @kikocorreoso 
Yo ahora entro en una temporada bastante frenética; y ni me puedo encargar ni voy a poder guiar me temo :cry:

**Comment by astrojuanlu** [comment]
Yo me dejo brasear @kikocorreoso: cuando lo tengamos aquí, lo metemos en
Pybonacci ;)

**Comment by kikocorreoso** [comment]
@Juanlu001 no da puntada sin hilo.

Si lo puedo hacer todo. Simplemente, a la hora de meter algunos settings y dockerizar alguna cosa pues prefiero que indiquen la forma pyes 'canónica' los que ya lo están haciendo.

Ok. a ver si me estudio isso, que entiendo necesitará una BD aunque con una sqlite en disco igual basta para el tráfico que hay.

**Comment by kikocorreoso** [comment]
WIP!!

**Comment by kikocorreoso** [comment]
Cerrado a petición de los socios :-P 

\o/
