### ISSUE TITLE
Agregar información sobre cómo contribuir a la web

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/web#55]
Sugerido por @aiup53r en https://github.com/python-spain/asociacion/issues/19:

> Añadir una guía sencilla para desarrolladores sobre cómo contribuir en la web. Por ejemplo: medio de organización, listado de tareas pendientes...

**Comment by delapuente** [comment]
Existe un documento [CONTRIBUTING.md](https://github.com/python-spain/web/blob/master/CONTRIBUTING.md). ¿Qué otras cosas creeis que faltan?

**Comment by astrojuanlu** [comment]
Pues, así leyéndolo en diagonal, nada :) ¡Gracias @delapuente!
