### ISSUE TITLE
Resaltar FreeWear en la página principal

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/web#63]
Tenemos una tienda en la que vendemos merchandising y recibimos donaciones pero está totalmente escondida. Se podría añadir algo en la web principal, un call to action, un ribbon, para que se viese mejor.

https://www.freewear.org/?page=list_items&org=PythonEspa%C3%B1a

**Comment by fcoterroba** [comment]
Buenas!
Voy a intentar hacerlo/tenerlo para antes de este finde! 🤟
Así de primeras lo que se me ocurre es hacerla como una page más y poquita cosa más. Aún así, miraré para hacerlo como me comentas, en un CtA, un Ribbon o algo similar.

**Comment by dukebody** [comment]
¡Hecho! Gracias @fcoterroba
