### ISSUE TITLE
Simplificar instrucciones de alta

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/web#64]
Simplificar el procedimiento es cosa de la asociación, pero simplificar las instrucciones del proceso actual es cosa de la web :)

Ya los simplificamos en su día (ver #57) pero parece que aún no está del todo claro, y además se dijo que es incierto si el correo lo recibe un humano.

| Antes |  Después |
|--------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------|
| ![screenshot_2018-10-09 hazte socio python espana](https://user-images.githubusercontent.com/316517/46669351-723bf180-cbcf-11e8-9726-f04e9c2fd4be.png) <sup>(nótese que la cuenta bancaria está más abajo)</sup> | ![screenshot_2018-10-09 hazte socio python espana 1](https://user-images.githubusercontent.com/316517/46669916-107c8700-cbd1-11e8-806d-32de036f4cf3.png) |

¿Qué os parece @python-spain/junta-directiva?

**Comment by mariocj89** [comment]
Si, cambiemoslo. :)

**Comment by maigimenez** [comment]
Me parece muchísimo mejor. Poquito a poco lo conseguiremos hacer super fácil.

**Comment by raulcd** [comment]
@dukebody esto se puede cerrar ya, no?

**Comment by dukebody** [comment]
¡Sí! Gracias por el ping.
