### ISSUE TITLE
Mejorando legibilidad

### ISSUE THREAD

**Issue by Manosfrias** [python-spain/web#65]
Os voy a pasar unas capturas de lo que llevo pero os pediría, porfa, que os fijéis en la tipografía sobre todo: he ampliado las tipos y las he hecho fluidas (me he basado en [este artículo](https://css-tricks.com/snippets/css/fluid-typography/)).

El resto de cambios, también espero que os gusten, pero es un un [WIP] (en la captura del tamaño móvil se puede comprobar que no anda todo muy fino).

De momento, estos cambios estoy subiéndolos a mi github. Estoy haciendo branchs (más o menos) por cada cambio que realizo. Si hay algo que os vaya gustando me decís para que pueda compartirlo aquí.

**Captura completa de un ancho de pantalla de 2193px**
![2193px-width tamano completo](https://user-images.githubusercontent.com/10085811/47114137-42d65600-d25b-11e8-8090-eeff99c39032.png)

**Captura completa de un ancho de pantalla de 320px**
![320px-width tamano completo](https://user-images.githubusercontent.com/10085811/47114197-70230400-d25b-11e8-9f9a-e24760fa51fa.png)

**Comment by astrojuanlu** [comment]
¡Muchas gracias @Manosfrias! Tienen muy buena pinta los cambios, a mí por lo menos me gustan mucho. ¿Si te parece podemos ir haciendo pull requests pequeños cuando vayas teniendo cosas terminadas? Por ejemplo, cuando tengas solucionado el overflow de los menús que se ve en la segunda captura. Y ojalá que estas renovaciones de diseño también hagan que haya más actividad en este repositorio :)

**Comment by maigimenez** [comment]
Hola @Manosfrias Lo primero ¡Muchísimas gracias por el trabajazo! 
Tengo un par de dudillas sobre las tipos en la versión 2193px que te comparto por si pueden ser de utilidad. 
- [ ] La primera es que creo que molaría tener la Flux Regular para display (título) ya que es la tipografía de la PSF, igual se le puede pedir a la PSF porque según lo que pone en su [manual de uso](https://www.python.org/community/logos/) se puede usar para cosas de la PSF y esto puede que cualifique. En cualquier caso, tampoco sería descabellado que la asociación la [comprara](https://www.linotype.com/es/275355/flux-regular-product.html) para poder emplearla.  
- [ ] Lo segundo es que aunque está bien jerarquizado el título se queda un poco pequeño el subtítulo "Web de la asociación" y cuando subas el cuerpo del subtítulo el interlineado se pegará demasido, porque ahora ya está justito. 
- [ ] Otra cosa que ve es que falta un aire a la maquetación, especialmente bajo el logo y el banner de las secciones y después entre las secciones y el artículo. Además el título del artículo debería ser o en el mismo gris que el empleado en "Python España" o un poco más claro para jerarquizar. 
- [ ] Y ya lo último y es de nota, la PSF utiliza [Source Sans](https://fonts.google.com/specimen/Source+Sans+Pro) en su web y es una tipo muy bonica libre que si la podemos usar molaría porque así se mantiene la coherencia de marca. 
Perdona por dejarte todo este texto. Recalcar que a pesar de los detalles a mejorar está muy bien y que te agradecemos infitnito tu trabajo.

**Comment by delapuente** [comment]
@maigimenez te he cambiado el comentario para convertirlo en _checklist_ y seguir mejor los cambios.

**Comment by dukebody** [comment]
@Manosfrias hola, ¿siguen existiendo estos problemas de legibilidad?

**Comment by dukebody** [comment]
Cierro esto por falta de actividad y porque tenemos pensado renovar el diseño de la web completamente.
