### ISSUE TITLE
Python Murcia no existe

### ISSUE THREAD

**Issue by flowsta** [python-spain/web#66]
El enlace de la comunidad de Python Murcia lleva a un Meetup que Meetup dice que no existe:
http://www.meetup.com/es-ES/Meetup-de-Python-en-Murcia/

**Comment by astrojuanlu** [comment]
Cierto, Meetup tiene esa maravillosa costumbre de borrar los meetups de la faz de la tierra cuando dejas de pagar.

Se aceptan pull requests :frowning_face:
