### ISSUE TITLE
Post PyConES Granada 2020

### ISSUE THREAD

**Issue by dukebody** [python-spain/web#77]
Post indicando que la próxima PyConES será en Granada, con enlaces para ponerse en contacto con la organización y apuntarse al grupo de voluntariado.

@Juanlu001 ¿puede escribir esto el equipo organizador?

**Comment by astrojuanlu** [comment]
¡Yo creo que sí!

**Comment by astrojuanlu** [comment]
Pero cuando la web esté publicada, me parece :)

**Comment by dukebody** [comment]
Timeout :)
