### ISSUE TITLE
Post indicando que existe Discourse

### ISSUE THREAD

**Issue by dukebody** [python-spain/web#78]
Es un punto de entrada muy importante a la participación.

@maigimenez ¿podrías escribir algo tú? ¿Dónde hay información indicando los motivos por qué se tomó la decisión y cuáles son las vías para apuntarse y conseguir el estatus de "socio/a"?

**Comment by dukebody** [comment]
Ejemplo:

Desde hace unos meses está disponible un [foro web](https://github.com/python-spain/web/issues) basado en Discourse como canal de comunicación entre la comunidad. 

Este sistema permite configurar subscripciones y notificaciones por sección/hilo/etc. para que estés al tanto de lo que te interesa sin perderte en un mar de ruido. :)

Podéis encontrar información sobre las tareas que se están llevando a cabo, ofertas de empleo, preguntas sobre Python y mucho más. 

Para obtener acceso a la sección exclusiva para socios/as escribe a [secretaria@es.python.org](mailto:secretaria@es.python.org).

**Comment by astrojuanlu** [comment]
La información sobre los motivos es básicamente:

> En línea con un esfuerzo que llevamos haciendo hace tiempo para 
mejorar nuestros canales de comunicación y con lo que está pasando en 
la comunidad Python global, vamos a archivar esta lista de correo y 
mover toda nuestra comunicación al nuevo Discourse

https://lists.es.python.org/private/socios/2019-May/001037.html (enlace privado para socies)

**Comment by dukebody** [comment]
Debemos dejar clara la existencia del foro en la nueva estructura. Cierro esto en favor de https://github.com/python-spain/web/issues/10.
