### ISSUE TITLE
Actualizar enlaces a actas

### ISSUE THREAD

**Issue by dukebody** [python-spain/web#79]
El enlace de la web en https://es.python.org/pages/asociacion.html lleva a un sitio donde hay actas muy viejas. Este es “yet another site” que mantener y da la sensación de que la asociación está medio muerta con actas tan viejas. Sustituir ese enlace por https://github.com/python-spain/actas 1. Quizá los estatutos también los deberíamos enlazar desde aquí.

@maigimenez ¿algún input sobre esto?

**Comment by dukebody** [comment]
El enlace con información desactualizada al que me refiero es http://documentos-asociacion.es.python.org/index.html. ¿Alguna idea del repo a partir del cual se genera esta página? ¿Podemos darla por muerta y enlazar siempre a documentos de https://github.com/python-spain/actas?

**Comment by dukebody** [comment]
> ¿Alguna idea del repo a partir del cual se genera esta página?

Me respondo a mí mismo: https://hg.es.python.org/asociacion/ . Yo creo que definitivamente se puede dar este repo por muerto y dirigir al repo de https://github.com/python-spain/actas en su lugar.

**Comment by dukebody** [comment]
@Juanlu001 quizá tú también tengas alguna idea sobre esto.

**Comment by astrojuanlu** [comment]
* [x] Jubilemos https://hg.es.python.org/asociacion/ (no lo enlacemos en ningún lado)
* [ ] Migremos los Estatutos, el Reglamento de Régimen Interno y el Código de Conducta aquí
* [x] Migremos http://documentos-asociacion.es.python.org/revisi%C3%B3n%20de%20estatutos%20y%20rri.html a issues aquí
* [ ] Decidamos qué hacer con el resto de los documentos
  - http://documentos-asociacion.es.python.org/procedimientos/gesti%C3%B3n%20de%20los%20documentos%20de%20la%20asociaci%C3%B3n.html desactualizado
  - http://documentos-asociacion.es.python.org/procedimientos/gesti%C3%B3n%20de%20actas%20de%20la%20Junta%20Directiva.html desactualizado
  - http://documentos-asociacion.es.python.org/procedimientos/alta%20y%20baja%20de%20miembros%20de%20la%20Junta%20Directiva.html desactualizado
  - http://documentos-asociacion.es.python.org/procedimientos/directrices%20reuniones%20a%20distancia.html podría ser útil tenerlo en algún sitio, ¿tal vez un mensaje anclado en Discourse? (previa revisión y actualización)
  - http://documentos-asociacion.es.python.org/procedimientos/acceso%20al%20repositorio%20Mercurial.html desactualizado
  - http://documentos-asociacion.es.python.org/procedimientos/listas%20de%20correo.html vacío
  - http://documentos-asociacion.es.python.org/procedimientos/webs%20est%C3%A1ticas.html desactualizado
  - http://documentos-asociacion.es.python.org/otros/criterios%20generales%20de%20la%20web%20PyConES.html estaría bien tenerlo en algún sitio pero habría que revisarlo 
* [ ] Jubilemos http://documentos-asociacion.es.python.org/ (no lo enlacemos en ningún sitio)

**Comment by dukebody** [comment]
>     * [ ]  Jubilemos https://hg.es.python.org/asociacion/ (no lo enlacemos en ningún lado)

En realidad sólo está enlazado desde http://documentos-asociacion.es.python.org/, así que asumo que está hecho.

>     * [ ]  Migremos los Estatutos, el Reglamento de Régimen Interno y el Código de Conducta aquí

Ver https://github.com/python-spain/actas/pull/24.

Paralelamente, el acta fundacional no estaba bien migrada. Ver https://github.com/python-spain/actas/pull/26.

>     * [ ]  Migremos http://documentos-asociacion.es.python.org/revisi%C3%B3n%20de%20estatutos%20y%20rri.html a issues aquí

Hecho: https://github.com/python-spain/actas/issues/25

>     * [ ]  Decidamos qué hacer con el resto de los documentos       

>       * http://documentos-asociacion.es.python.org/procedimientos/directrices%20reuniones%20a%20distancia.html podría ser útil tenerlo en algún sitio, ¿tal vez un mensaje anclado en Discourse? (previa revisión y actualización)

Yo creo que lo que dice este documento es relativamente de sentido común. No sé si merece la pena darle muchas vueltas y ponerlo en ningún sitio.

>       * http://documentos-asociacion.es.python.org/otros/criterios%20generales%20de%20la%20web%20PyConES.html estaría bien tenerlo en algún sitio pero habría que revisarlo

Le he pasado la tarea al grupo de trabajo de la PyConES: https://comunidad.es.python.org/t/documentacion-sobre-criterios-generales-de-la-web-pycones/208
 
>     * [ ]  Jubilemos http://documentos-asociacion.es.python.org/ (no lo enlacemos en ningún sitio)

En cuanto se haga merge de los PRs que he citado hacemos merge de https://github.com/python-spain/web/pull/81.

**Comment by dukebody** [comment]
¡Esto está hecho! La parte de criterios generales de la web está desactualizada y no merece la pena reutilizarla ahora mismo en mi opinión.
