### ISSUE TITLE
Nueva figura de miembro

### ISSUE THREAD

**Issue by quobit** [python-spain/web#82]
Hace unos meses se aprobó un cambio en los estatutos sobre la figura de _miembro_  de la asociación pero este nuevo perfil no se refleja en la web.

**Comment by astrojuanlu** [comment]
Se aprobó el cambio pero aún no se ha hecho efectivo. Posiblemente será la última cosa que haga la JD saliente... en enero y después de cerrar la actual PyConES.

**Comment by maigimenez** [comment]
En principio debe aprobarse el cambio en los estatutos en asamblea general. En cuanto este trámite esté finalizado se podrá añadir la nueva figura a la web.

**Comment by dukebody** [comment]
Queremos poner un formulario para que la gente se apunte como miembro: https://github.com/python-spain/asociacion/issues/135

**Comment by dukebody** [comment]
La seguimos en https://github.com/python-spain/web-ng/issues/98.
