### ISSUE TITLE
Añadir enlace a documentación en español para aprender Python

### ISSUE THREAD

**Issue by dukebody** [python-spain/web#93]
Si se mantiene en https://wiki.python.org/moin/SpanishLanguage por visibilidad, deberíamos enlazarla desde la web de la asociación.

**Comment by fcoterroba** [comment]
Buenas! No he podido ponerme antes con la issue pero hoy tengo todo el día!

La cosa es que me gustaría lanzar una pregunta al aire para ver cómo plantearíais vosotros dónde poner la wiki? En el pie de página? En el encabezado? Hacer una entrada más? 

@dukebody

**Comment by dukebody** [comment]
@fcoterroba ¡Qué bien que te apetezca seguir participando! Siento no haber podido mirar esto antes.

Creo que la forma más sencilla es crear una página más, igual que hiciste con "merchandising". Puedes llamarla "aprende python". Se pueden copiar/pegar las secciones relevantes del mensaje de FAQ que se enlaza en el canal de Python en español: https://telegra.ph/Preguntas-frecuentes-11-13:
- Qué libros y cursos se recomiendan para empezar. Aquí se puede añadir https://wiki.python.org/moin/SpanishLanguage.
- Dónde conseguir ayuda (canales de Telegram y más)

¿Cómo lo ves?
